sudo: required

services:
  - docker

language: python3

script:
  - pytest beswican/tests -m core

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh